name:                haskcell-lib
version:             0.2.1.1
github:              "ignaciobll/haskcell-lib"
license:             BSD3
author:              "Ignacio Ballesteros"
maintainer:          "ignacioballesterosgonzalez@gmail.com"
copyright:           "2018 Ignacio Ballesteros"

extra-source-files:
- README.md
- examples/*
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ignaciobll/haskcell-lib#readme>

dependencies:
- base >= 4.7 && < 5
- time
# - cassava
# - bytestring
# - vector
# - text
- matrix
- containers
# - directory
- QuickCheck
# - quickcheck-properties == 0.1
- hspec
# - hspec-discover
- checkers
- hspec-checkers

library:
  source-dirs: src

executables:
  example-expenses:
    main:                Expenses.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Weverything
    # - -Wall
    - -main-is Expenses
    dependencies:
    - haskcell-lib

tests:
  haskcell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskcell-lib
